[package]
name = "common-rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]

[features]
default = ["restful", "config", "consul", "sm"]
config = ["dep:config", "dep:reqwest"]
consul = ["dep:reqwest"]
restful = ["dep:axum", "dep:serde", "dep:serde_json", "dep:tokio"]
sm = ["dep:efficient-sm2", "dep:libsm"]

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", optional = true }
config = { version = "0.13", optional = true }
efficient-sm2 = { version = "0.2", optional = true }
figment = { version = "0.10", features = ["toml"] }
notify = { version = "6.1", features = ["serde"] }
parking_lot = "0.12"
libsm = { version = "0.5", optional = true }
reqwest = { version = "0.11", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
tokio = { version = "1.34", features = ["signal", "macros"], optional = true }
tracing = "0.1"
